/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Deliverable = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'fileType' : IDL.Opt(IDL.Text),
  'uploadedAt' : Timestamp,
});
export const EntryType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const GalleryVideoInput = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'isVisible' : IDL.Bool,
});
export const GalleryVideo = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'isVisible' : IDL.Bool,
  'uploadedAt' : Timestamp,
});
export const PayoutStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const PayoutRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : PayoutStatus,
  'method' : IDL.Text,
  'processedAt' : IDL.Opt(Timestamp),
  'affiliateId' : IDL.Text,
  'adjustmentNote' : IDL.Text,
  'amount' : IDL.Float64,
  'requestedAt' : Timestamp,
  'adjustedBy' : IDL.Opt(IDL.Principal),
});
export const SystemApp = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isVisible' : IDL.Bool,
});
export const ConsultingTier = IDL.Variant({
  'BakerySetupAndRecipes' : IDL.Null,
  'BusinessDevelopment' : IDL.Null,
  'Advisory' : IDL.Null,
  'BakerySetup' : IDL.Null,
});
export const CreateProjectRequest = IDL.Record({
  'clientName' : IDL.Text,
  'projectDescription' : IDL.Text,
  'tier' : ConsultingTier,
  'clientEmail' : IDL.Text,
  'clientPrincipal' : IDL.Principal,
  'projectTitle' : IDL.Text,
  'expectedEndDate' : IDL.Opt(Timestamp),
  'startDate' : Timestamp,
});
export const AffiliateStats = IDL.Record({
  'totalLeads' : IDL.Nat,
  'totalClicks' : IDL.Nat,
  'totalConversions' : IDL.Nat,
  'totalCommissionEarned' : IDL.Float64,
  'pendingPayout' : IDL.Float64,
});
export const AffiliateStatus = IDL.Variant({
  'pending' : IDL.Null,
  'disabled' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AffiliateProfile = IDL.Record({
  'status' : AffiliateStatus,
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'inviteCode' : IDL.Text,
});
export const ContactPlatform = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'platformKey' : IDL.Text,
  'displayLabel' : IDL.Opt(IDL.Text),
  'isVisible' : IDL.Bool,
  'platformName' : IDL.Text,
});
export const LegalContent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const ClientProjectStatus = IDL.Variant({
  'OnHold' : IDL.Null,
  'UnderReview' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const NextStep = IDL.Record({
  'id' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'order' : IDL.Nat,
  'description' : IDL.Text,
});
export const ProjectUpdate = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : Timestamp,
});
export const ClientProject = IDL.Record({
  'id' : IDL.Text,
  'completedDate' : IDL.Opt(Timestamp),
  'status' : ClientProjectStatus,
  'nextSteps' : IDL.Vec(NextStep),
  'clientName' : IDL.Text,
  'projectDescription' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : ConsultingTier,
  'clientEmail' : IDL.Text,
  'clientPrincipal' : IDL.Principal,
  'updatedAt' : Timestamp,
  'projectTitle' : IDL.Text,
  'updates' : IDL.Vec(ProjectUpdate),
  'deliverables' : IDL.Vec(Deliverable),
  'expectedEndDate' : IDL.Opt(Timestamp),
  'startDate' : Timestamp,
});
export const Testimonial = IDL.Record({
  'role' : IDL.Text,
  'text' : IDL.Text,
  'author' : IDL.Text,
  'isVisible' : IDL.Bool,
});
export const BlockEntry = IDL.Record({
  'key' : IDL.Text,
  'blockedAt' : IDL.Int,
  'reason' : IDL.Text,
});
export const CompetenceCard = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isVisible' : IDL.Bool,
});
export const ContactLinks = IDL.Record({
  'primaryCtaText' : IDL.Text,
  'instagram' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'facebook' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'messageText' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
});
export const CryptoPaymentConfig = IDL.Record({
  'usdcEnabled' : IDL.Bool,
  'paymentInstructions' : IDL.Text,
  'network' : IDL.Text,
  'usdtWalletAddress' : IDL.Text,
  'eligibleOfferIds' : IDL.Vec(IDL.Text),
  'usdcWalletAddress' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const DeploymentEntry = IDL.Record({
  'deployedAt' : IDL.Int,
  'note' : IDL.Text,
  'version' : IDL.Nat,
});
export const FinanceEntry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : EntryType,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const FinanceSummary = IDL.Record({
  'entryCount' : IDL.Nat,
  'totalIncome' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'netBalance' : IDL.Int,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'storageId' : IDL.Text,
  'caption' : IDL.Text,
  'uploadedAt' : Timestamp,
});
export const HeroImageIds = IDL.Record({
  'presenceImageId' : IDL.Opt(IDL.Text),
  'slide3ImageId' : IDL.Opt(IDL.Text),
  'aboutImageId' : IDL.Opt(IDL.Text),
  'slide1ImageId' : IDL.Opt(IDL.Text),
  'slide2ImageId' : IDL.Opt(IDL.Text),
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'rejected' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const LeadSource = IDL.Variant({
  'other' : IDL.Null,
  'training_enrollment' : IDL.Null,
  'contact_form' : IDL.Null,
  'affiliate_signup' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : LeadStatus,
  'source' : LeadSource,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'affiliateRef' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'message' : IDL.Text,
  'notes' : IDL.Text,
  'assignedStaff' : IDL.Opt(IDL.Principal),
  'phone' : IDL.Opt(IDL.Text),
});
export const LeadStats = IDL.Record({
  'totalLeads' : IDL.Nat,
  'newLeads' : IDL.Nat,
  'qualifiedLeads' : IDL.Nat,
});
export const LeadFilter = IDL.Record({
  'status' : IDL.Opt(LeadStatus),
  'source' : IDL.Opt(LeadSource),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'assignedStaff' : IDL.Opt(IDL.Principal),
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : IDL.Text,
  'assignedStaff' : IDL.Opt(IDL.Principal),
  'customerId' : IDL.Opt(IDL.Principal),
  'amount' : IDL.Float64,
  'customerEmail' : IDL.Text,
  'product' : IDL.Text,
});
export const SalesFilter = IDL.Record({
  'status' : IDL.Opt(OrderStatus),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'assignedStaff' : IDL.Opt(IDL.Principal),
  'product' : IDL.Opt(IDL.Text),
});
export const LocalBankConfig = IDL.Record({
  'bankName' : IDL.Text,
  'accountName' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const PaystackConfig = IDL.Record({
  'webhookSecret' : IDL.Text,
  'publicKey' : IDL.Text,
  'secretKey' : IDL.Text,
});
export const FlutterwaveConfig = IDL.Record({
  'webhookSecret' : IDL.Text,
  'publicKey' : IDL.Text,
  'secretKey' : IDL.Text,
});
export const PaymentConfig = IDL.Record({
  'localBank' : IDL.Opt(LocalBankConfig),
  'servicePriceNgn' : IDL.Nat,
  'updatedAt' : Timestamp,
  'enabledMethods' : IDL.Vec(
    IDL.Variant({
      'localBank' : IDL.Null,
      'paystack' : IDL.Null,
      'flutterwave' : IDL.Null,
    })
  ),
  'paystack' : IDL.Opt(PaystackConfig),
  'defaultCurrency' : IDL.Text,
  'flutterwave' : IDL.Opt(FlutterwaveConfig),
});
export const GiveawayItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'isActive' : IDL.Bool,
  'currency' : IDL.Text,
  'isVisible' : IDL.Bool,
  'discountedPrice' : IDL.Opt(IDL.Nat),
});
export const Bundle = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'bundlePrice' : IDL.Nat,
  'currency' : IDL.Text,
  'includedServiceIds' : IDL.Vec(IDL.Text),
  'isVisible' : IDL.Bool,
});
export const LandingPageOffer = IDL.Record({
  'id' : IDL.Text,
  'tag' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'tier' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'isVisible' : IDL.Bool,
  'price' : IDL.Nat,
});
export const ConsultancyService = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'isVisible' : IDL.Bool,
  'price' : IDL.Nat,
});
export const CompetencePricing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'shortDescription' : IDL.Text,
  'currency' : IDL.Text,
  'isVisible' : IDL.Bool,
  'price' : IDL.Nat,
});
export const PricingData = IDL.Record({
  'giveaways' : IDL.Vec(GiveawayItem),
  'bundles' : IDL.Vec(Bundle),
  'landingPageOffers' : IDL.Vec(LandingPageOffer),
  'consultancyServices' : IDL.Vec(ConsultancyService),
  'competencePricing' : IDL.Vec(CompetencePricing),
});
export const SalesStats = IDL.Record({
  'pendingPayments' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
});
export const SecurityPolicy = IDL.Record({
  'sessionTimeoutMins' : IDL.Nat,
  'maxLoginAttempts' : IDL.Nat,
  'rateLimitPerMin' : IDL.Nat,
  'rateLimitPublicPerMin' : IDL.Nat,
  'lockoutDurationMins' : IDL.Nat,
});
export const TrainingModule = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'videoStorageId' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'textContent' : IDL.Text,
});
export const IpAddress = IDL.Text;
export const UserRole = IDL.Variant({
  'Customer' : IDL.Null,
  'Staff' : IDL.Null,
  'PlatformOwner' : IDL.Null,
  'Affiliate' : IDL.Null,
  'Admin' : IDL.Null,
});
export const AuditAction = IDL.Variant({
  'Login' : IDL.Null,
  'AccessDenied' : IDL.Null,
  'Approve' : IDL.Null,
  'Reject' : IDL.Null,
  'Logout' : IDL.Null,
  'Delete' : IDL.Null,
  'Create' : IDL.Null,
  'Update' : IDL.Null,
});
export const AuditLog = IDL.Record({
  'ip' : IDL.Opt(IpAddress),
  'userRole' : UserRole,
  'resource' : IDL.Text,
  'action' : AuditAction,
  'userId' : IDL.Principal,
  'logId' : IDL.Nat,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
});
export const BuyerLeadStatus = IDL.Variant({
  'New' : IDL.Null,
  'Contacted' : IDL.Null,
  'Converted' : IDL.Null,
  'Rejected' : IDL.Null,
});
export const FormSource = IDL.Variant({
  'Hero' : IDL.Null,
  'Footer' : IDL.Null,
  'MidPage' : IDL.Null,
});
export const BuyerLead = IDL.Record({
  'id' : IDL.Nat,
  'status' : BuyerLeadStatus,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'projectDescription' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'formSource' : FormSource,
  'phone' : IDL.Text,
  'budgetRange' : IDL.Text,
  'timeline' : IDL.Text,
});
export const PaymentOrderStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Rejected' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentOrder = IDL.Record({
  'status' : PaymentOrderStatus,
  'method' : IDL.Variant({
    'localBank' : IDL.Null,
    'paystack' : IDL.Null,
    'flutterwave' : IDL.Null,
  }),
  'payerEmail' : IDL.Text,
  'approvedBy' : IDL.Opt(IDL.Principal),
  'createdAt' : Timestamp,
  'payerPhone' : IDL.Opt(IDL.Text),
  'orderId' : IDL.Nat,
  'updatedAt' : Timestamp,
  'currency' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'payerName' : IDL.Text,
  'webhookRef' : IDL.Opt(IDL.Text),
});
export const AboutSection = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
});
export const CommissionSettings = IDL.Record({
  'defaultRate' : IDL.Float64,
  'overrideRates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const ContactLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
export const ContactDetails = IDL.Record({
  'x' : IDL.Opt(IDL.Text),
  'linkedin' : IDL.Opt(IDL.Text),
  'snapchat' : IDL.Opt(IDL.Text),
  'tiktok' : IDL.Opt(IDL.Text),
  'otherLinks' : IDL.Vec(ContactLink),
  'instagram' : IDL.Opt(IDL.Text),
  'whatsapp' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'facebook' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const HelpBlock = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const SlideButton = IDL.Record({ 'href' : IDL.Text, 'text' : IDL.Text });
export const HeroSlide = IDL.Record({
  'body' : IDL.Text,
  'headline' : IDL.Text,
  'button1' : SlideButton,
  'button2' : SlideButton,
  'subheadline' : IDL.Text,
});
export const SignatureEdge = IDL.Record({
  'quote' : IDL.Text,
  'pillar1' : IDL.Text,
  'pillar2' : IDL.Text,
  'pillar3' : IDL.Text,
});
export const UpdateProjectRequest = IDL.Record({
  'completedDate' : IDL.Opt(Timestamp),
  'status' : IDL.Opt(ClientProjectStatus),
  'projectDescription' : IDL.Opt(IDL.Text),
  'projectTitle' : IDL.Opt(IDL.Text),
  'expectedEndDate' : IDL.Opt(Timestamp),
});
export const SystemConfig = IDL.Record({
  'siteTitle' : IDL.Text,
  'ctaGetLandingPage' : IDL.Text,
  'brandTagline' : IDL.Text,
  'maintenanceMode' : IDL.Bool,
  'siteDescription' : IDL.Text,
  'environment' : IDL.Text,
  'heroHeadline' : IDL.Text,
  'ctaWorkWithMe' : IDL.Text,
  'competenceSectionVisible' : IDL.Bool,
  'ctaExploreSystems' : IDL.Text,
  'heroSubtext' : IDL.Text,
  'footerText' : IDL.Text,
  'ctaViewCompetence' : IDL.Text,
});
export const Permission = IDL.Variant({
  'CanViewReports' : IDL.Null,
  'CanManageRoles' : IDL.Null,
  'CanManageTraining' : IDL.Null,
  'CanManageMedia' : IDL.Null,
  'CanManageBuyerLeads' : IDL.Null,
  'CanManagePayments' : IDL.Null,
  'CanViewDashboard' : IDL.Null,
  'CanManageSecurity' : IDL.Null,
  'CanManageLeads' : IDL.Null,
  'CanManageSales' : IDL.Null,
  'CanManageFinance' : IDL.Null,
  'CanManageStaff' : IDL.Null,
  'CanEditContent' : IDL.Null,
  'CanViewAuditLog' : IDL.Null,
  'CanManageAffiliates' : IDL.Null,
  'CanEditContactDetails' : IDL.Null,
});
export const RoleResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ActivityLog = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'actorRole' : UserRole,
  'actorId' : IDL.Principal,
  'target' : IDL.Text,
  'timestamp' : Timestamp,
  'ipAddress' : IDL.Opt(IpAddress),
});
export const LiveSession = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'joinLink' : IDL.Text,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const PaymentConfigPublic = IDL.Record({
  'localBank' : IDL.Opt(LocalBankConfig),
  'servicePriceNgn' : IDL.Nat,
  'paystackPublicKey' : IDL.Opt(IDL.Text),
  'enabledMethods' : IDL.Vec(
    IDL.Variant({
      'localBank' : IDL.Null,
      'paystack' : IDL.Null,
      'flutterwave' : IDL.Null,
    })
  ),
  'defaultCurrency' : IDL.Text,
  'flutterwavePublicKey' : IDL.Opt(IDL.Text),
});
export const CryptoPaymentPublic = IDL.Record({
  'usdcEnabled' : IDL.Bool,
  'paymentInstructions' : IDL.Text,
  'network' : IDL.Text,
  'usdtWalletAddress' : IDL.Text,
  'usdcWalletAddress' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const VersionInfo = IDL.Record({
  'systemVersion' : IDL.Text,
  'buildVersion' : IDL.Nat,
  'lastDeployedAt' : IDL.Int,
  'environment' : IDL.Text,
});
export const StaffUser = IDL.Record({
  'id' : IDL.Principal,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
  }),
  'permissions' : IDL.Vec(Permission),
  'lastLoginAt' : IDL.Opt(Timestamp),
  'role' : UserRole,
  'invitedAt' : Timestamp,
  'email' : IDL.Text,
});
export const SubmitResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_internalCreateLeadFromContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Int],
      [],
      ['oneway'],
    ),
  'adminAddDeliverable' : IDL.Func(
      [IDL.Text, Deliverable],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAddFinanceEntry' : IDL.Func(
      [EntryType, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'adminAddGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAddGalleryVideo' : IDL.Func(
      [GalleryVideoInput],
      [IDL.Variant({ 'ok' : GalleryVideo, 'err' : IDL.Text })],
      [],
    ),
  'adminAddNextStep' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAddOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Principal),
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminAddPayout' : IDL.Func(
      [PayoutRecord],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminAddSystemApp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : SystemApp, 'err' : IDL.Text })],
      [],
    ),
  'adminAddUpdate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAdjustCommission' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveAffiliate' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminApprovePaymentOrder' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminBlockKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminCreateLiveSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'adminCreateProject' : IDL.Func(
      [CreateProjectRequest],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateTrainingModule' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'adminDeleteFinanceEntry' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteGalleryVideo' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteLiveSession' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteSystemApp' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteTrainingModule' : IDL.Func([IDL.Nat], [], []),
  'adminDisableAffiliate' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminEditGalleryVideo' : IDL.Func(
      [IDL.Nat, GalleryVideoInput],
      [IDL.Variant({ 'ok' : GalleryVideo, 'err' : IDL.Text })],
      [],
    ),
  'adminEditSystemApp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAffiliateStats' : IDL.Func([IDL.Text], [AffiliateStats], []),
  'adminGetAffiliates' : IDL.Func([], [IDL.Vec(AffiliateProfile)], []),
  'adminGetAllContactPlatforms' : IDL.Func([], [IDL.Vec(ContactPlatform)], []),
  'adminGetAllLegalContent' : IDL.Func([], [IDL.Vec(LegalContent)], []),
  'adminGetAllProjects' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(ClientProject), 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], []),
  'adminGetBlockedKeys' : IDL.Func([], [IDL.Vec(BlockEntry)], []),
  'adminGetBrandTagline' : IDL.Func([], [IDL.Text], []),
  'adminGetCompetenceCards' : IDL.Func([], [IDL.Vec(CompetenceCard)], []),
  'adminGetCompetenceSectionVisible' : IDL.Func([], [IDL.Bool], []),
  'adminGetContactLinks' : IDL.Func([], [ContactLinks], []),
  'adminGetContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
  'adminGetCryptoPaymentConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : CryptoPaymentConfig, 'err' : IDL.Text })],
      [],
    ),
  'adminGetDeploymentLog' : IDL.Func([], [IDL.Vec(DeploymentEntry)], []),
  'adminGetFinanceEntries' : IDL.Func([], [IDL.Vec(FinanceEntry)], []),
  'adminGetFinanceSummary' : IDL.Func([], [FinanceSummary], []),
  'adminGetGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], []),
  'adminGetGalleryVideos' : IDL.Func([], [IDL.Vec(GalleryVideo)], []),
  'adminGetHeroImageIds' : IDL.Func([], [HeroImageIds], []),
  'adminGetLead' : IDL.Func([IDL.Text], [IDL.Opt(Lead)], []),
  'adminGetLeadStats' : IDL.Func([], [LeadStats], []),
  'adminGetLeads' : IDL.Func([LeadFilter], [IDL.Vec(Lead)], []),
  'adminGetOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], []),
  'adminGetOrders' : IDL.Func([SalesFilter], [IDL.Vec(Order)], []),
  'adminGetPaymentConfig' : IDL.Func([], [PaymentConfig], []),
  'adminGetPayoutHistory' : IDL.Func([IDL.Text], [IDL.Vec(PayoutRecord)], []),
  'adminGetPricingData' : IDL.Func([], [PricingData], []),
  'adminGetProjectById' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ClientProject, 'err' : IDL.Text })],
      [],
    ),
  'adminGetSalesStats' : IDL.Func([], [SalesStats], []),
  'adminGetSecurityPolicy' : IDL.Func([], [SecurityPolicy], []),
  'adminGetSystemsApps' : IDL.Func([], [IDL.Vec(SystemApp)], []),
  'adminGetTrainingModules' : IDL.Func([], [IDL.Vec(TrainingModule)], []),
  'adminListAuditLogs' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(AuditLog)], []),
  'adminListBuyerLeads' : IDL.Func(
      [IDL.Opt(BuyerLeadStatus), IDL.Opt(FormSource)],
      [IDL.Vec(BuyerLead)],
      [],
    ),
  'adminListPaymentOrders' : IDL.Func([], [IDL.Vec(PaymentOrder)], []),
  'adminRegisterAffiliate' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'adminRejectAffiliate' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminReorderPlatform' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetAbout' : IDL.Func([AboutSection], [], []),
  'adminSetBrandTagline' : IDL.Func([IDL.Text], [], []),
  'adminSetBundles' : IDL.Func(
      [IDL.Vec(Bundle)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetCommission' : IDL.Func(
      [CommissionSettings],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetCompetenceCards' : IDL.Func([IDL.Vec(CompetenceCard)], [], []),
  'adminSetCompetencePricing' : IDL.Func(
      [IDL.Vec(CompetencePricing)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetCompetenceSectionVisible' : IDL.Func([IDL.Bool], [], []),
  'adminSetConsultancyServices' : IDL.Func(
      [IDL.Vec(ConsultancyService)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetContactDetails' : IDL.Func(
      [ContactDetails],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetContactLinks' : IDL.Func([ContactLinks], [], []),
  'adminSetContactPlatforms' : IDL.Func(
      [IDL.Vec(ContactPlatform)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetCryptoPaymentConfig' : IDL.Func(
      [CryptoPaymentConfig],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetGiveaways' : IDL.Func(
      [IDL.Vec(GiveawayItem)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetHelpBlocks' : IDL.Func([IDL.Vec(HelpBlock)], [], []),
  'adminSetHeroImageIds' : IDL.Func([HeroImageIds], [], []),
  'adminSetHeroSlides' : IDL.Func([IDL.Vec(HeroSlide)], [], []),
  'adminSetLandingPageOffers' : IDL.Func(
      [IDL.Vec(LandingPageOffer)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetLegalContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSetPaymentConfig' : IDL.Func(
      [PaymentConfig],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetSecurityPolicy' : IDL.Func(
      [SecurityPolicy],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetSignatureEdge' : IDL.Func([SignatureEdge], [], []),
  'adminSetTestimonials' : IDL.Func([IDL.Vec(Testimonial)], [], []),
  'adminSetWebhookSecretHash' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminToggleGalleryVideoFeatured' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : GalleryVideo, 'err' : IDL.Text })],
      [],
    ),
  'adminToggleGalleryVideoVisibility' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : GalleryVideo, 'err' : IDL.Text })],
      [],
    ),
  'adminTogglePlatformVisibility' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'adminTogglePricingItemVisibility' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'adminToggleSystemApp' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'adminUnblockKey' : IDL.Func([IDL.Text], [], []),
  'adminUpdateBuyerLeadStatus' : IDL.Func(
      [IDL.Nat, BuyerLeadStatus, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        LeadSource,
        LeadStatus,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Text),
        IDL.Int,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateLiveSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'adminUpdateNextStep' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        OrderStatus,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Principal),
        IDL.Int,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdatePayoutRecord' : IDL.Func(
      [IDL.Text, PayoutStatus, IDL.Opt(IDL.Principal), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateProject' : IDL.Func(
      [IDL.Text, UpdateProjectRequest],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateSystemConfig' : IDL.Func(
      [SystemConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateTrainingModule' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'affiliateGetInviteLink' : IDL.Func([], [IDL.Text], []),
  'affiliateGetPayoutHistory' : IDL.Func([], [IDL.Vec(PayoutRecord)], []),
  'affiliateGetProfile' : IDL.Func([], [AffiliateProfile], []),
  'affiliateGetStats' : IDL.Func([], [AffiliateStats], []),
  'affiliateRequestPayout' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'assignUserRole' : IDL.Func(
      [IDL.Principal, UserRole, IDL.Text, IDL.Vec(Permission)],
      [RoleResult],
      [],
    ),
  'claimOwnership' : IDL.Func([IDL.Text], [RoleResult], []),
  'clientGetMyProject' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : ClientProject, 'err' : IDL.Text })],
      [],
    ),
  'confirmOwnership' : IDL.Func(
      [],
      [IDL.Record({ 'role' : IDL.Opt(UserRole), 'isOwnerOrAdmin' : IDL.Bool })],
      [],
    ),
  'createPaymentOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Variant({
          'localBank' : IDL.Null,
          'paystack' : IDL.Null,
          'flutterwave' : IDL.Null,
        }),
      ],
      [IDL.Variant({ 'ok' : PaymentOrder, 'err' : IDL.Text })],
      [],
    ),
  'flutterwaveWebhook' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAbout' : IDL.Func([], [AboutSection], ['query']),
  'getActivityLog' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityLog)], []),
  'getBrandTagline' : IDL.Func([], [IDL.Text], ['query']),
  'getCompetenceCards' : IDL.Func([], [IDL.Vec(CompetenceCard)], ['query']),
  'getCompetenceCardsVisible' : IDL.Func(
      [],
      [IDL.Vec(CompetenceCard)],
      ['query'],
    ),
  'getCompetenceSectionVisible' : IDL.Func([], [IDL.Bool], ['query']),
  'getContactDetails' : IDL.Func([], [ContactDetails], ['query']),
  'getContactLinks' : IDL.Func([], [ContactLinks], ['query']),
  'getContactPlatforms' : IDL.Func([], [IDL.Vec(ContactPlatform)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getGalleryVideos' : IDL.Func([], [IDL.Vec(GalleryVideo)], ['query']),
  'getHelpBlocks' : IDL.Func([], [IDL.Vec(HelpBlock)], ['query']),
  'getHeroImageIds' : IDL.Func([], [HeroImageIds], ['query']),
  'getHeroSlides' : IDL.Func([], [IDL.Vec(HeroSlide)], ['query']),
  'getLegalContent' : IDL.Func([IDL.Text], [IDL.Opt(LegalContent)], ['query']),
  'getLiveSessions' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(UserRole)], []),
  'getOwnerDebugInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'ownerEmail' : IDL.Text,
          'callerRole' : IDL.Text,
          'callerIsOwner' : IDL.Bool,
          'callerEmail' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getPaymentConfig' : IDL.Func([], [PaymentConfigPublic], ['query']),
  'getPricingData' : IDL.Func([], [PricingData], ['query']),
  'getPublicCryptoPaymentInfo' : IDL.Func(
      [],
      [IDL.Opt(CryptoPaymentPublic)],
      ['query'],
    ),
  'getSignatureEdge' : IDL.Func([], [SignatureEdge], ['query']),
  'getSystemConfig' : IDL.Func([], [SystemConfig], ['query']),
  'getSystemsApps' : IDL.Func([], [IDL.Vec(SystemApp)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTrainingModules' : IDL.Func([], [IDL.Vec(TrainingModule)], []),
  'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], []),
  'getVersionInfo' : IDL.Func([], [VersionInfo], ['query']),
  'getVisibleTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'listUsersByRole' : IDL.Func([UserRole], [IDL.Vec(StaffUser)], []),
  'paystackWebhook' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'revokeUserRole' : IDL.Func([IDL.Principal], [RoleResult], []),
  'submitBuyerLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        FormSource,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SubmitResult],
      [],
    ),
  'trackReferralClick' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Deliverable = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'fileType' : IDL.Opt(IDL.Text),
    'uploadedAt' : Timestamp,
  });
  const EntryType = IDL.Variant({ 'expense' : IDL.Null, 'income' : IDL.Null });
  const GalleryVideoInput = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'isVisible' : IDL.Bool,
  });
  const GalleryVideo = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'isVisible' : IDL.Bool,
    'uploadedAt' : Timestamp,
  });
  const PayoutStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const PayoutRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : PayoutStatus,
    'method' : IDL.Text,
    'processedAt' : IDL.Opt(Timestamp),
    'affiliateId' : IDL.Text,
    'adjustmentNote' : IDL.Text,
    'amount' : IDL.Float64,
    'requestedAt' : Timestamp,
    'adjustedBy' : IDL.Opt(IDL.Principal),
  });
  const SystemApp = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isVisible' : IDL.Bool,
  });
  const ConsultingTier = IDL.Variant({
    'BakerySetupAndRecipes' : IDL.Null,
    'BusinessDevelopment' : IDL.Null,
    'Advisory' : IDL.Null,
    'BakerySetup' : IDL.Null,
  });
  const CreateProjectRequest = IDL.Record({
    'clientName' : IDL.Text,
    'projectDescription' : IDL.Text,
    'tier' : ConsultingTier,
    'clientEmail' : IDL.Text,
    'clientPrincipal' : IDL.Principal,
    'projectTitle' : IDL.Text,
    'expectedEndDate' : IDL.Opt(Timestamp),
    'startDate' : Timestamp,
  });
  const AffiliateStats = IDL.Record({
    'totalLeads' : IDL.Nat,
    'totalClicks' : IDL.Nat,
    'totalConversions' : IDL.Nat,
    'totalCommissionEarned' : IDL.Float64,
    'pendingPayout' : IDL.Float64,
  });
  const AffiliateStatus = IDL.Variant({
    'pending' : IDL.Null,
    'disabled' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AffiliateProfile = IDL.Record({
    'status' : AffiliateStatus,
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'inviteCode' : IDL.Text,
  });
  const ContactPlatform = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'platformKey' : IDL.Text,
    'displayLabel' : IDL.Opt(IDL.Text),
    'isVisible' : IDL.Bool,
    'platformName' : IDL.Text,
  });
  const LegalContent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const ClientProjectStatus = IDL.Variant({
    'OnHold' : IDL.Null,
    'UnderReview' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const NextStep = IDL.Record({
    'id' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'order' : IDL.Nat,
    'description' : IDL.Text,
  });
  const ProjectUpdate = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : Timestamp,
  });
  const ClientProject = IDL.Record({
    'id' : IDL.Text,
    'completedDate' : IDL.Opt(Timestamp),
    'status' : ClientProjectStatus,
    'nextSteps' : IDL.Vec(NextStep),
    'clientName' : IDL.Text,
    'projectDescription' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : ConsultingTier,
    'clientEmail' : IDL.Text,
    'clientPrincipal' : IDL.Principal,
    'updatedAt' : Timestamp,
    'projectTitle' : IDL.Text,
    'updates' : IDL.Vec(ProjectUpdate),
    'deliverables' : IDL.Vec(Deliverable),
    'expectedEndDate' : IDL.Opt(Timestamp),
    'startDate' : Timestamp,
  });
  const Testimonial = IDL.Record({
    'role' : IDL.Text,
    'text' : IDL.Text,
    'author' : IDL.Text,
    'isVisible' : IDL.Bool,
  });
  const BlockEntry = IDL.Record({
    'key' : IDL.Text,
    'blockedAt' : IDL.Int,
    'reason' : IDL.Text,
  });
  const CompetenceCard = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isVisible' : IDL.Bool,
  });
  const ContactLinks = IDL.Record({
    'primaryCtaText' : IDL.Text,
    'instagram' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'facebook' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'messageText' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
  });
  const CryptoPaymentConfig = IDL.Record({
    'usdcEnabled' : IDL.Bool,
    'paymentInstructions' : IDL.Text,
    'network' : IDL.Text,
    'usdtWalletAddress' : IDL.Text,
    'eligibleOfferIds' : IDL.Vec(IDL.Text),
    'usdcWalletAddress' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const DeploymentEntry = IDL.Record({
    'deployedAt' : IDL.Int,
    'note' : IDL.Text,
    'version' : IDL.Nat,
  });
  const FinanceEntry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : EntryType,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const FinanceSummary = IDL.Record({
    'entryCount' : IDL.Nat,
    'totalIncome' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'netBalance' : IDL.Int,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'storageId' : IDL.Text,
    'caption' : IDL.Text,
    'uploadedAt' : Timestamp,
  });
  const HeroImageIds = IDL.Record({
    'presenceImageId' : IDL.Opt(IDL.Text),
    'slide3ImageId' : IDL.Opt(IDL.Text),
    'aboutImageId' : IDL.Opt(IDL.Text),
    'slide1ImageId' : IDL.Opt(IDL.Text),
    'slide2ImageId' : IDL.Opt(IDL.Text),
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'rejected' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const LeadSource = IDL.Variant({
    'other' : IDL.Null,
    'training_enrollment' : IDL.Null,
    'contact_form' : IDL.Null,
    'affiliate_signup' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : LeadStatus,
    'source' : LeadSource,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'affiliateRef' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'message' : IDL.Text,
    'notes' : IDL.Text,
    'assignedStaff' : IDL.Opt(IDL.Principal),
    'phone' : IDL.Opt(IDL.Text),
  });
  const LeadStats = IDL.Record({
    'totalLeads' : IDL.Nat,
    'newLeads' : IDL.Nat,
    'qualifiedLeads' : IDL.Nat,
  });
  const LeadFilter = IDL.Record({
    'status' : IDL.Opt(LeadStatus),
    'source' : IDL.Opt(LeadSource),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'assignedStaff' : IDL.Opt(IDL.Principal),
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notes' : IDL.Text,
    'assignedStaff' : IDL.Opt(IDL.Principal),
    'customerId' : IDL.Opt(IDL.Principal),
    'amount' : IDL.Float64,
    'customerEmail' : IDL.Text,
    'product' : IDL.Text,
  });
  const SalesFilter = IDL.Record({
    'status' : IDL.Opt(OrderStatus),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'assignedStaff' : IDL.Opt(IDL.Principal),
    'product' : IDL.Opt(IDL.Text),
  });
  const LocalBankConfig = IDL.Record({
    'bankName' : IDL.Text,
    'accountName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const PaystackConfig = IDL.Record({
    'webhookSecret' : IDL.Text,
    'publicKey' : IDL.Text,
    'secretKey' : IDL.Text,
  });
  const FlutterwaveConfig = IDL.Record({
    'webhookSecret' : IDL.Text,
    'publicKey' : IDL.Text,
    'secretKey' : IDL.Text,
  });
  const PaymentConfig = IDL.Record({
    'localBank' : IDL.Opt(LocalBankConfig),
    'servicePriceNgn' : IDL.Nat,
    'updatedAt' : Timestamp,
    'enabledMethods' : IDL.Vec(
      IDL.Variant({
        'localBank' : IDL.Null,
        'paystack' : IDL.Null,
        'flutterwave' : IDL.Null,
      })
    ),
    'paystack' : IDL.Opt(PaystackConfig),
    'defaultCurrency' : IDL.Text,
    'flutterwave' : IDL.Opt(FlutterwaveConfig),
  });
  const GiveawayItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'isActive' : IDL.Bool,
    'currency' : IDL.Text,
    'isVisible' : IDL.Bool,
    'discountedPrice' : IDL.Opt(IDL.Nat),
  });
  const Bundle = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'bundlePrice' : IDL.Nat,
    'currency' : IDL.Text,
    'includedServiceIds' : IDL.Vec(IDL.Text),
    'isVisible' : IDL.Bool,
  });
  const LandingPageOffer = IDL.Record({
    'id' : IDL.Text,
    'tag' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'tier' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'isVisible' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const ConsultancyService = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'isVisible' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const CompetencePricing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'shortDescription' : IDL.Text,
    'currency' : IDL.Text,
    'isVisible' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const PricingData = IDL.Record({
    'giveaways' : IDL.Vec(GiveawayItem),
    'bundles' : IDL.Vec(Bundle),
    'landingPageOffers' : IDL.Vec(LandingPageOffer),
    'consultancyServices' : IDL.Vec(ConsultancyService),
    'competencePricing' : IDL.Vec(CompetencePricing),
  });
  const SalesStats = IDL.Record({
    'pendingPayments' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
  });
  const SecurityPolicy = IDL.Record({
    'sessionTimeoutMins' : IDL.Nat,
    'maxLoginAttempts' : IDL.Nat,
    'rateLimitPerMin' : IDL.Nat,
    'rateLimitPublicPerMin' : IDL.Nat,
    'lockoutDurationMins' : IDL.Nat,
  });
  const TrainingModule = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'videoStorageId' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'textContent' : IDL.Text,
  });
  const IpAddress = IDL.Text;
  const UserRole = IDL.Variant({
    'Customer' : IDL.Null,
    'Staff' : IDL.Null,
    'PlatformOwner' : IDL.Null,
    'Affiliate' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const AuditAction = IDL.Variant({
    'Login' : IDL.Null,
    'AccessDenied' : IDL.Null,
    'Approve' : IDL.Null,
    'Reject' : IDL.Null,
    'Logout' : IDL.Null,
    'Delete' : IDL.Null,
    'Create' : IDL.Null,
    'Update' : IDL.Null,
  });
  const AuditLog = IDL.Record({
    'ip' : IDL.Opt(IpAddress),
    'userRole' : UserRole,
    'resource' : IDL.Text,
    'action' : AuditAction,
    'userId' : IDL.Principal,
    'logId' : IDL.Nat,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
  });
  const BuyerLeadStatus = IDL.Variant({
    'New' : IDL.Null,
    'Contacted' : IDL.Null,
    'Converted' : IDL.Null,
    'Rejected' : IDL.Null,
  });
  const FormSource = IDL.Variant({
    'Hero' : IDL.Null,
    'Footer' : IDL.Null,
    'MidPage' : IDL.Null,
  });
  const BuyerLead = IDL.Record({
    'id' : IDL.Nat,
    'status' : BuyerLeadStatus,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'projectDescription' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'formSource' : FormSource,
    'phone' : IDL.Text,
    'budgetRange' : IDL.Text,
    'timeline' : IDL.Text,
  });
  const PaymentOrderStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Rejected' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentOrder = IDL.Record({
    'status' : PaymentOrderStatus,
    'method' : IDL.Variant({
      'localBank' : IDL.Null,
      'paystack' : IDL.Null,
      'flutterwave' : IDL.Null,
    }),
    'payerEmail' : IDL.Text,
    'approvedBy' : IDL.Opt(IDL.Principal),
    'createdAt' : Timestamp,
    'payerPhone' : IDL.Opt(IDL.Text),
    'orderId' : IDL.Nat,
    'updatedAt' : Timestamp,
    'currency' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'payerName' : IDL.Text,
    'webhookRef' : IDL.Opt(IDL.Text),
  });
  const AboutSection = IDL.Record({ 'bio' : IDL.Text, 'title' : IDL.Text });
  const CommissionSettings = IDL.Record({
    'defaultRate' : IDL.Float64,
    'overrideRates' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const ContactLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const ContactDetails = IDL.Record({
    'x' : IDL.Opt(IDL.Text),
    'linkedin' : IDL.Opt(IDL.Text),
    'snapchat' : IDL.Opt(IDL.Text),
    'tiktok' : IDL.Opt(IDL.Text),
    'otherLinks' : IDL.Vec(ContactLink),
    'instagram' : IDL.Opt(IDL.Text),
    'whatsapp' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'facebook' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const HelpBlock = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const SlideButton = IDL.Record({ 'href' : IDL.Text, 'text' : IDL.Text });
  const HeroSlide = IDL.Record({
    'body' : IDL.Text,
    'headline' : IDL.Text,
    'button1' : SlideButton,
    'button2' : SlideButton,
    'subheadline' : IDL.Text,
  });
  const SignatureEdge = IDL.Record({
    'quote' : IDL.Text,
    'pillar1' : IDL.Text,
    'pillar2' : IDL.Text,
    'pillar3' : IDL.Text,
  });
  const UpdateProjectRequest = IDL.Record({
    'completedDate' : IDL.Opt(Timestamp),
    'status' : IDL.Opt(ClientProjectStatus),
    'projectDescription' : IDL.Opt(IDL.Text),
    'projectTitle' : IDL.Opt(IDL.Text),
    'expectedEndDate' : IDL.Opt(Timestamp),
  });
  const SystemConfig = IDL.Record({
    'siteTitle' : IDL.Text,
    'ctaGetLandingPage' : IDL.Text,
    'brandTagline' : IDL.Text,
    'maintenanceMode' : IDL.Bool,
    'siteDescription' : IDL.Text,
    'environment' : IDL.Text,
    'heroHeadline' : IDL.Text,
    'ctaWorkWithMe' : IDL.Text,
    'competenceSectionVisible' : IDL.Bool,
    'ctaExploreSystems' : IDL.Text,
    'heroSubtext' : IDL.Text,
    'footerText' : IDL.Text,
    'ctaViewCompetence' : IDL.Text,
  });
  const Permission = IDL.Variant({
    'CanViewReports' : IDL.Null,
    'CanManageRoles' : IDL.Null,
    'CanManageTraining' : IDL.Null,
    'CanManageMedia' : IDL.Null,
    'CanManageBuyerLeads' : IDL.Null,
    'CanManagePayments' : IDL.Null,
    'CanViewDashboard' : IDL.Null,
    'CanManageSecurity' : IDL.Null,
    'CanManageLeads' : IDL.Null,
    'CanManageSales' : IDL.Null,
    'CanManageFinance' : IDL.Null,
    'CanManageStaff' : IDL.Null,
    'CanEditContent' : IDL.Null,
    'CanViewAuditLog' : IDL.Null,
    'CanManageAffiliates' : IDL.Null,
    'CanEditContactDetails' : IDL.Null,
  });
  const RoleResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ActivityLog = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'actorRole' : UserRole,
    'actorId' : IDL.Principal,
    'target' : IDL.Text,
    'timestamp' : Timestamp,
    'ipAddress' : IDL.Opt(IpAddress),
  });
  const LiveSession = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'joinLink' : IDL.Text,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const PaymentConfigPublic = IDL.Record({
    'localBank' : IDL.Opt(LocalBankConfig),
    'servicePriceNgn' : IDL.Nat,
    'paystackPublicKey' : IDL.Opt(IDL.Text),
    'enabledMethods' : IDL.Vec(
      IDL.Variant({
        'localBank' : IDL.Null,
        'paystack' : IDL.Null,
        'flutterwave' : IDL.Null,
      })
    ),
    'defaultCurrency' : IDL.Text,
    'flutterwavePublicKey' : IDL.Opt(IDL.Text),
  });
  const CryptoPaymentPublic = IDL.Record({
    'usdcEnabled' : IDL.Bool,
    'paymentInstructions' : IDL.Text,
    'network' : IDL.Text,
    'usdtWalletAddress' : IDL.Text,
    'usdcWalletAddress' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const VersionInfo = IDL.Record({
    'systemVersion' : IDL.Text,
    'buildVersion' : IDL.Nat,
    'lastDeployedAt' : IDL.Int,
    'environment' : IDL.Text,
  });
  const StaffUser = IDL.Record({
    'id' : IDL.Principal,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'pending' : IDL.Null,
      'inactive' : IDL.Null,
    }),
    'permissions' : IDL.Vec(Permission),
    'lastLoginAt' : IDL.Opt(Timestamp),
    'role' : UserRole,
    'invitedAt' : Timestamp,
    'email' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    '_internalCreateLeadFromContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Int],
        [],
        ['oneway'],
      ),
    'adminAddDeliverable' : IDL.Func(
        [IDL.Text, Deliverable],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAddFinanceEntry' : IDL.Func(
        [EntryType, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'adminAddGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAddGalleryVideo' : IDL.Func(
        [GalleryVideoInput],
        [IDL.Variant({ 'ok' : GalleryVideo, 'err' : IDL.Text })],
        [],
      ),
    'adminAddNextStep' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAddOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Principal),
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminAddPayout' : IDL.Func(
        [PayoutRecord],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminAddSystemApp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : SystemApp, 'err' : IDL.Text })],
        [],
      ),
    'adminAddUpdate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAdjustCommission' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveAffiliate' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminApprovePaymentOrder' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminBlockKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminCreateLiveSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'adminCreateProject' : IDL.Func(
        [CreateProjectRequest],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateTrainingModule' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'adminDeleteFinanceEntry' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteGalleryVideo' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteLiveSession' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteSystemApp' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteTrainingModule' : IDL.Func([IDL.Nat], [], []),
    'adminDisableAffiliate' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminEditGalleryVideo' : IDL.Func(
        [IDL.Nat, GalleryVideoInput],
        [IDL.Variant({ 'ok' : GalleryVideo, 'err' : IDL.Text })],
        [],
      ),
    'adminEditSystemApp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAffiliateStats' : IDL.Func([IDL.Text], [AffiliateStats], []),
    'adminGetAffiliates' : IDL.Func([], [IDL.Vec(AffiliateProfile)], []),
    'adminGetAllContactPlatforms' : IDL.Func(
        [],
        [IDL.Vec(ContactPlatform)],
        [],
      ),
    'adminGetAllLegalContent' : IDL.Func([], [IDL.Vec(LegalContent)], []),
    'adminGetAllProjects' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(ClientProject), 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], []),
    'adminGetBlockedKeys' : IDL.Func([], [IDL.Vec(BlockEntry)], []),
    'adminGetBrandTagline' : IDL.Func([], [IDL.Text], []),
    'adminGetCompetenceCards' : IDL.Func([], [IDL.Vec(CompetenceCard)], []),
    'adminGetCompetenceSectionVisible' : IDL.Func([], [IDL.Bool], []),
    'adminGetContactLinks' : IDL.Func([], [ContactLinks], []),
    'adminGetContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
    'adminGetCryptoPaymentConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : CryptoPaymentConfig, 'err' : IDL.Text })],
        [],
      ),
    'adminGetDeploymentLog' : IDL.Func([], [IDL.Vec(DeploymentEntry)], []),
    'adminGetFinanceEntries' : IDL.Func([], [IDL.Vec(FinanceEntry)], []),
    'adminGetFinanceSummary' : IDL.Func([], [FinanceSummary], []),
    'adminGetGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], []),
    'adminGetGalleryVideos' : IDL.Func([], [IDL.Vec(GalleryVideo)], []),
    'adminGetHeroImageIds' : IDL.Func([], [HeroImageIds], []),
    'adminGetLead' : IDL.Func([IDL.Text], [IDL.Opt(Lead)], []),
    'adminGetLeadStats' : IDL.Func([], [LeadStats], []),
    'adminGetLeads' : IDL.Func([LeadFilter], [IDL.Vec(Lead)], []),
    'adminGetOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], []),
    'adminGetOrders' : IDL.Func([SalesFilter], [IDL.Vec(Order)], []),
    'adminGetPaymentConfig' : IDL.Func([], [PaymentConfig], []),
    'adminGetPayoutHistory' : IDL.Func([IDL.Text], [IDL.Vec(PayoutRecord)], []),
    'adminGetPricingData' : IDL.Func([], [PricingData], []),
    'adminGetProjectById' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ClientProject, 'err' : IDL.Text })],
        [],
      ),
    'adminGetSalesStats' : IDL.Func([], [SalesStats], []),
    'adminGetSecurityPolicy' : IDL.Func([], [SecurityPolicy], []),
    'adminGetSystemsApps' : IDL.Func([], [IDL.Vec(SystemApp)], []),
    'adminGetTrainingModules' : IDL.Func([], [IDL.Vec(TrainingModule)], []),
    'adminListAuditLogs' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(AuditLog)],
        [],
      ),
    'adminListBuyerLeads' : IDL.Func(
        [IDL.Opt(BuyerLeadStatus), IDL.Opt(FormSource)],
        [IDL.Vec(BuyerLead)],
        [],
      ),
    'adminListPaymentOrders' : IDL.Func([], [IDL.Vec(PaymentOrder)], []),
    'adminRegisterAffiliate' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'adminRejectAffiliate' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminReorderPlatform' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetAbout' : IDL.Func([AboutSection], [], []),
    'adminSetBrandTagline' : IDL.Func([IDL.Text], [], []),
    'adminSetBundles' : IDL.Func(
        [IDL.Vec(Bundle)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetCommission' : IDL.Func(
        [CommissionSettings],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetCompetenceCards' : IDL.Func([IDL.Vec(CompetenceCard)], [], []),
    'adminSetCompetencePricing' : IDL.Func(
        [IDL.Vec(CompetencePricing)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetCompetenceSectionVisible' : IDL.Func([IDL.Bool], [], []),
    'adminSetConsultancyServices' : IDL.Func(
        [IDL.Vec(ConsultancyService)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetContactDetails' : IDL.Func(
        [ContactDetails],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetContactLinks' : IDL.Func([ContactLinks], [], []),
    'adminSetContactPlatforms' : IDL.Func(
        [IDL.Vec(ContactPlatform)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetCryptoPaymentConfig' : IDL.Func(
        [CryptoPaymentConfig],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetGiveaways' : IDL.Func(
        [IDL.Vec(GiveawayItem)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetHelpBlocks' : IDL.Func([IDL.Vec(HelpBlock)], [], []),
    'adminSetHeroImageIds' : IDL.Func([HeroImageIds], [], []),
    'adminSetHeroSlides' : IDL.Func([IDL.Vec(HeroSlide)], [], []),
    'adminSetLandingPageOffers' : IDL.Func(
        [IDL.Vec(LandingPageOffer)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetLegalContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSetPaymentConfig' : IDL.Func(
        [PaymentConfig],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetSecurityPolicy' : IDL.Func(
        [SecurityPolicy],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetSignatureEdge' : IDL.Func([SignatureEdge], [], []),
    'adminSetTestimonials' : IDL.Func([IDL.Vec(Testimonial)], [], []),
    'adminSetWebhookSecretHash' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminToggleGalleryVideoFeatured' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : GalleryVideo, 'err' : IDL.Text })],
        [],
      ),
    'adminToggleGalleryVideoVisibility' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : GalleryVideo, 'err' : IDL.Text })],
        [],
      ),
    'adminTogglePlatformVisibility' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'adminTogglePricingItemVisibility' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'adminToggleSystemApp' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'adminUnblockKey' : IDL.Func([IDL.Text], [], []),
    'adminUpdateBuyerLeadStatus' : IDL.Func(
        [IDL.Nat, BuyerLeadStatus, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          LeadSource,
          LeadStatus,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Text),
          IDL.Int,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateLiveSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'adminUpdateNextStep' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          OrderStatus,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Principal),
          IDL.Int,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdatePayoutRecord' : IDL.Func(
        [IDL.Text, PayoutStatus, IDL.Opt(IDL.Principal), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateProject' : IDL.Func(
        [IDL.Text, UpdateProjectRequest],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateSystemConfig' : IDL.Func(
        [SystemConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateTrainingModule' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'affiliateGetInviteLink' : IDL.Func([], [IDL.Text], []),
    'affiliateGetPayoutHistory' : IDL.Func([], [IDL.Vec(PayoutRecord)], []),
    'affiliateGetProfile' : IDL.Func([], [AffiliateProfile], []),
    'affiliateGetStats' : IDL.Func([], [AffiliateStats], []),
    'affiliateRequestPayout' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'assignUserRole' : IDL.Func(
        [IDL.Principal, UserRole, IDL.Text, IDL.Vec(Permission)],
        [RoleResult],
        [],
      ),
    'claimOwnership' : IDL.Func([IDL.Text], [RoleResult], []),
    'clientGetMyProject' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : ClientProject, 'err' : IDL.Text })],
        [],
      ),
    'confirmOwnership' : IDL.Func(
        [],
        [
          IDL.Record({
            'role' : IDL.Opt(UserRole),
            'isOwnerOrAdmin' : IDL.Bool,
          }),
        ],
        [],
      ),
    'createPaymentOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Variant({
            'localBank' : IDL.Null,
            'paystack' : IDL.Null,
            'flutterwave' : IDL.Null,
          }),
        ],
        [IDL.Variant({ 'ok' : PaymentOrder, 'err' : IDL.Text })],
        [],
      ),
    'flutterwaveWebhook' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAbout' : IDL.Func([], [AboutSection], ['query']),
    'getActivityLog' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityLog)], []),
    'getBrandTagline' : IDL.Func([], [IDL.Text], ['query']),
    'getCompetenceCards' : IDL.Func([], [IDL.Vec(CompetenceCard)], ['query']),
    'getCompetenceCardsVisible' : IDL.Func(
        [],
        [IDL.Vec(CompetenceCard)],
        ['query'],
      ),
    'getCompetenceSectionVisible' : IDL.Func([], [IDL.Bool], ['query']),
    'getContactDetails' : IDL.Func([], [ContactDetails], ['query']),
    'getContactLinks' : IDL.Func([], [ContactLinks], ['query']),
    'getContactPlatforms' : IDL.Func([], [IDL.Vec(ContactPlatform)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getGalleryVideos' : IDL.Func([], [IDL.Vec(GalleryVideo)], ['query']),
    'getHelpBlocks' : IDL.Func([], [IDL.Vec(HelpBlock)], ['query']),
    'getHeroImageIds' : IDL.Func([], [HeroImageIds], ['query']),
    'getHeroSlides' : IDL.Func([], [IDL.Vec(HeroSlide)], ['query']),
    'getLegalContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LegalContent)],
        ['query'],
      ),
    'getLiveSessions' : IDL.Func([], [IDL.Vec(LiveSession)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(UserRole)], []),
    'getOwnerDebugInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'ownerEmail' : IDL.Text,
            'callerRole' : IDL.Text,
            'callerIsOwner' : IDL.Bool,
            'callerEmail' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getPaymentConfig' : IDL.Func([], [PaymentConfigPublic], ['query']),
    'getPricingData' : IDL.Func([], [PricingData], ['query']),
    'getPublicCryptoPaymentInfo' : IDL.Func(
        [],
        [IDL.Opt(CryptoPaymentPublic)],
        ['query'],
      ),
    'getSignatureEdge' : IDL.Func([], [SignatureEdge], ['query']),
    'getSystemConfig' : IDL.Func([], [SystemConfig], ['query']),
    'getSystemsApps' : IDL.Func([], [IDL.Vec(SystemApp)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTrainingModules' : IDL.Func([], [IDL.Vec(TrainingModule)], []),
    'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], []),
    'getVersionInfo' : IDL.Func([], [VersionInfo], ['query']),
    'getVisibleTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'listUsersByRole' : IDL.Func([UserRole], [IDL.Vec(StaffUser)], []),
    'paystackWebhook' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'revokeUserRole' : IDL.Func([IDL.Principal], [RoleResult], []),
    'submitBuyerLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          FormSource,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SubmitResult],
        [],
      ),
    'trackReferralClick' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };