/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection { 'bio' : string, 'title' : string }
export interface ActivityLog {
  'id' : string,
  'action' : string,
  'actorRole' : UserRole,
  'actorId' : Principal,
  'target' : string,
  'timestamp' : Timestamp,
  'ipAddress' : [] | [IpAddress],
}
export interface AffiliateProfile {
  'status' : AffiliateStatus,
  'principal' : Principal,
  'referralCode' : string,
  'name' : string,
  'joinedAt' : Timestamp,
  'rejectionReason' : [] | [string],
  'email' : string,
  'inviteCode' : string,
}
export interface AffiliateStats {
  'totalLeads' : bigint,
  'totalClicks' : bigint,
  'totalConversions' : bigint,
  'totalCommissionEarned' : number,
  'pendingPayout' : number,
}
export type AffiliateStatus = { 'pending' : null } |
  { 'disabled' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AuditAction = { 'Login' : null } |
  { 'AccessDenied' : null } |
  { 'Approve' : null } |
  { 'Reject' : null } |
  { 'Logout' : null } |
  { 'Delete' : null } |
  { 'Create' : null } |
  { 'Update' : null };
export interface AuditLog {
  'ip' : [] | [IpAddress],
  'userRole' : UserRole,
  'resource' : string,
  'action' : AuditAction,
  'userId' : Principal,
  'logId' : bigint,
  'timestamp' : Timestamp,
  'details' : string,
}
export interface BlockEntry {
  'key' : string,
  'blockedAt' : bigint,
  'reason' : string,
}
export interface Bundle {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'bundlePrice' : bigint,
  'currency' : string,
  'includedServiceIds' : Array<string>,
  'isVisible' : boolean,
}
export interface BuyerLead {
  'id' : bigint,
  'status' : BuyerLeadStatus,
  'assignedTo' : [] | [Principal],
  'projectDescription' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'businessName' : string,
  'businessType' : string,
  'email' : string,
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
  'formSource' : FormSource,
  'phone' : string,
  'budgetRange' : string,
  'timeline' : string,
}
export type BuyerLeadStatus = { 'New' : null } |
  { 'Contacted' : null } |
  { 'Converted' : null } |
  { 'Rejected' : null };
export interface ClientProject {
  'id' : string,
  'completedDate' : [] | [Timestamp],
  'status' : ClientProjectStatus,
  'nextSteps' : Array<NextStep>,
  'clientName' : string,
  'projectDescription' : string,
  'createdAt' : Timestamp,
  'tier' : ConsultingTier,
  'clientEmail' : string,
  'clientPrincipal' : Principal,
  'updatedAt' : Timestamp,
  'projectTitle' : string,
  'updates' : Array<ProjectUpdate>,
  'deliverables' : Array<Deliverable>,
  'expectedEndDate' : [] | [Timestamp],
  'startDate' : Timestamp,
}
export type ClientProjectStatus = { 'OnHold' : null } |
  { 'UnderReview' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface CommissionSettings {
  'defaultRate' : number,
  'overrideRates' : Array<[string, number]>,
}
export interface CompetenceCard {
  'title' : string,
  'description' : string,
  'isVisible' : boolean,
}
export interface CompetencePricing {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'shortDescription' : string,
  'currency' : string,
  'isVisible' : boolean,
  'price' : bigint,
}
export interface ConsultancyService {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'currency' : string,
  'isVisible' : boolean,
  'price' : bigint,
}
export type ConsultingTier = { 'BakerySetupAndRecipes' : null } |
  { 'BusinessDevelopment' : null } |
  { 'Advisory' : null } |
  { 'BakerySetup' : null };
export interface ContactDetails {
  'x' : [] | [string],
  'linkedin' : [] | [string],
  'snapchat' : [] | [string],
  'tiktok' : [] | [string],
  'otherLinks' : Array<ContactLink>,
  'instagram' : [] | [string],
  'whatsapp' : [] | [string],
  'email' : [] | [string],
  'updatedAt' : Timestamp,
  'facebook' : [] | [string],
  'phone' : [] | [string],
}
export interface ContactLink { 'url' : string, 'name' : string }
export interface ContactLinks {
  'primaryCtaText' : string,
  'instagram' : string,
  'whatsapp' : string,
  'email' : string,
  'facebook' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'messageText' : string,
  'timestamp' : bigint,
  'senderName' : string,
}
export interface ContactPlatform {
  'id' : string,
  'url' : string,
  'order' : bigint,
  'platformKey' : string,
  'displayLabel' : [] | [string],
  'isVisible' : boolean,
  'platformName' : string,
}
export interface CreateProjectRequest {
  'clientName' : string,
  'projectDescription' : string,
  'tier' : ConsultingTier,
  'clientEmail' : string,
  'clientPrincipal' : Principal,
  'projectTitle' : string,
  'expectedEndDate' : [] | [Timestamp],
  'startDate' : Timestamp,
}
export interface CryptoPaymentConfig {
  'usdcEnabled' : boolean,
  'paymentInstructions' : string,
  'network' : string,
  'usdtWalletAddress' : string,
  'eligibleOfferIds' : Array<string>,
  'usdcWalletAddress' : string,
  'enabled' : boolean,
}
export interface CryptoPaymentPublic {
  'usdcEnabled' : boolean,
  'paymentInstructions' : string,
  'network' : string,
  'usdtWalletAddress' : string,
  'usdcWalletAddress' : string,
  'enabled' : boolean,
}
export interface Deliverable {
  'id' : string,
  'url' : [] | [string],
  'title' : string,
  'isAvailable' : boolean,
  'description' : string,
  'fileType' : [] | [string],
  'uploadedAt' : Timestamp,
}
export interface DeploymentEntry {
  'deployedAt' : bigint,
  'note' : string,
  'version' : bigint,
}
export type EntryType = { 'expense' : null } |
  { 'income' : null };
export interface FinanceEntry {
  'id' : bigint,
  'entryType' : EntryType,
  'date' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'amount' : bigint,
}
export interface FinanceSummary {
  'entryCount' : bigint,
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
  'netBalance' : bigint,
}
export interface FlutterwaveConfig {
  'webhookSecret' : string,
  'publicKey' : string,
  'secretKey' : string,
}
export type FormSource = { 'Hero' : null } |
  { 'Footer' : null } |
  { 'MidPage' : null };
export interface GalleryImage {
  'id' : bigint,
  'storageId' : string,
  'caption' : string,
  'uploadedAt' : Timestamp,
}
export interface GalleryVideo {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'description' : string,
  'isFeatured' : boolean,
  'isVisible' : boolean,
  'uploadedAt' : Timestamp,
}
export interface GalleryVideoInput {
  'url' : string,
  'title' : string,
  'description' : string,
  'isFeatured' : boolean,
  'isVisible' : boolean,
}
export interface GiveawayItem {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'isFree' : boolean,
  'isActive' : boolean,
  'currency' : string,
  'isVisible' : boolean,
  'discountedPrice' : [] | [bigint],
}
export interface HelpBlock { 'title' : string, 'description' : string }
export interface HeroImageIds {
  'presenceImageId' : [] | [string],
  'slide3ImageId' : [] | [string],
  'aboutImageId' : [] | [string],
  'slide1ImageId' : [] | [string],
  'slide2ImageId' : [] | [string],
}
export interface HeroSlide {
  'body' : string,
  'headline' : string,
  'button1' : SlideButton,
  'button2' : SlideButton,
  'subheadline' : string,
}
export type IpAddress = string;
export interface LandingPageOffer {
  'id' : string,
  'tag' : [] | [string],
  'title' : string,
  'tier' : string,
  'description' : string,
  'currency' : string,
  'isVisible' : boolean,
  'price' : bigint,
}
export interface Lead {
  'id' : string,
  'status' : LeadStatus,
  'source' : LeadSource,
  'name' : string,
  'createdAt' : Timestamp,
  'affiliateRef' : [] | [string],
  'email' : string,
  'updatedAt' : Timestamp,
  'message' : string,
  'notes' : string,
  'assignedStaff' : [] | [Principal],
  'phone' : [] | [string],
}
export interface LeadFilter {
  'status' : [] | [LeadStatus],
  'source' : [] | [LeadSource],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'assignedStaff' : [] | [Principal],
}
export type LeadSource = { 'other' : null } |
  { 'training_enrollment' : null } |
  { 'contact_form' : null } |
  { 'affiliate_signup' : null };
export interface LeadStats {
  'totalLeads' : bigint,
  'newLeads' : bigint,
  'qualifiedLeads' : bigint,
}
export type LeadStatus = { 'new' : null } |
  { 'rejected' : null } |
  { 'contacted' : null } |
  { 'converted' : null } |
  { 'qualified' : null };
export interface LegalContent {
  'id' : string,
  'title' : string,
  'content' : string,
  'lastUpdated' : bigint,
}
export interface LiveSession {
  'id' : bigint,
  'title' : string,
  'joinLink' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : string,
}
export interface LocalBankConfig {
  'bankName' : string,
  'accountName' : string,
  'accountNumber' : string,
}
export interface NextStep {
  'id' : string,
  'isCompleted' : boolean,
  'order' : bigint,
  'description' : string,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : string,
  'assignedStaff' : [] | [Principal],
  'customerId' : [] | [Principal],
  'amount' : number,
  'customerEmail' : string,
  'product' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface PaymentConfig {
  'localBank' : [] | [LocalBankConfig],
  'servicePriceNgn' : bigint,
  'updatedAt' : Timestamp,
  'enabledMethods' : Array<
    { 'localBank' : null } |
      { 'paystack' : null } |
      { 'flutterwave' : null }
  >,
  'paystack' : [] | [PaystackConfig],
  'defaultCurrency' : string,
  'flutterwave' : [] | [FlutterwaveConfig],
}
export interface PaymentConfigPublic {
  'localBank' : [] | [LocalBankConfig],
  'servicePriceNgn' : bigint,
  'paystackPublicKey' : [] | [string],
  'enabledMethods' : Array<
    { 'localBank' : null } |
      { 'paystack' : null } |
      { 'flutterwave' : null }
  >,
  'defaultCurrency' : string,
  'flutterwavePublicKey' : [] | [string],
}
export interface PaymentOrder {
  'status' : PaymentOrderStatus,
  'method' : { 'localBank' : null } |
    { 'paystack' : null } |
    { 'flutterwave' : null },
  'payerEmail' : string,
  'approvedBy' : [] | [Principal],
  'createdAt' : Timestamp,
  'payerPhone' : [] | [string],
  'orderId' : bigint,
  'updatedAt' : Timestamp,
  'currency' : string,
  'notes' : [] | [string],
  'amount' : bigint,
  'payerName' : string,
  'webhookRef' : [] | [string],
}
export type PaymentOrderStatus = { 'Failed' : null } |
  { 'Rejected' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface PayoutRecord {
  'id' : string,
  'status' : PayoutStatus,
  'method' : string,
  'processedAt' : [] | [Timestamp],
  'affiliateId' : string,
  'adjustmentNote' : string,
  'amount' : number,
  'requestedAt' : Timestamp,
  'adjustedBy' : [] | [Principal],
}
export type PayoutStatus = { 'pending' : null } |
  { 'completed' : null };
export interface PaystackConfig {
  'webhookSecret' : string,
  'publicKey' : string,
  'secretKey' : string,
}
export type Permission = { 'CanViewReports' : null } |
  { 'CanManageRoles' : null } |
  { 'CanManageTraining' : null } |
  { 'CanManageMedia' : null } |
  { 'CanManageBuyerLeads' : null } |
  { 'CanManagePayments' : null } |
  { 'CanViewDashboard' : null } |
  { 'CanManageSecurity' : null } |
  { 'CanManageLeads' : null } |
  { 'CanManageSales' : null } |
  { 'CanManageFinance' : null } |
  { 'CanManageStaff' : null } |
  { 'CanEditContent' : null } |
  { 'CanViewAuditLog' : null } |
  { 'CanManageAffiliates' : null } |
  { 'CanEditContactDetails' : null };
export interface PricingData {
  'giveaways' : Array<GiveawayItem>,
  'bundles' : Array<Bundle>,
  'landingPageOffers' : Array<LandingPageOffer>,
  'consultancyServices' : Array<ConsultancyService>,
  'competencePricing' : Array<CompetencePricing>,
}
export interface ProjectUpdate {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : Timestamp,
}
export type RoleResult = { 'ok' : string } |
  { 'err' : string };
export interface SalesFilter {
  'status' : [] | [OrderStatus],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'assignedStaff' : [] | [Principal],
  'product' : [] | [string],
}
export interface SalesStats {
  'pendingPayments' : bigint,
  'totalOrders' : bigint,
  'totalRevenue' : number,
}
export interface SecurityPolicy {
  'sessionTimeoutMins' : bigint,
  'maxLoginAttempts' : bigint,
  'rateLimitPerMin' : bigint,
  'rateLimitPublicPerMin' : bigint,
  'lockoutDurationMins' : bigint,
}
export interface SignatureEdge {
  'quote' : string,
  'pillar1' : string,
  'pillar2' : string,
  'pillar3' : string,
}
export interface SlideButton { 'href' : string, 'text' : string }
export interface StaffUser {
  'id' : Principal,
  'status' : { 'active' : null } |
    { 'pending' : null } |
    { 'inactive' : null },
  'permissions' : Array<Permission>,
  'lastLoginAt' : [] | [Timestamp],
  'role' : UserRole,
  'invitedAt' : Timestamp,
  'email' : string,
}
export type SubmitResult = { 'ok' : string } |
  { 'err' : string };
export interface SystemApp {
  'id' : string,
  'url' : string,
  'order' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isVisible' : boolean,
}
export interface SystemConfig {
  'siteTitle' : string,
  'ctaGetLandingPage' : string,
  'brandTagline' : string,
  'maintenanceMode' : boolean,
  'siteDescription' : string,
  'environment' : string,
  'heroHeadline' : string,
  'ctaWorkWithMe' : string,
  'competenceSectionVisible' : boolean,
  'ctaExploreSystems' : string,
  'heroSubtext' : string,
  'footerText' : string,
  'ctaViewCompetence' : string,
}
export interface Testimonial {
  'role' : string,
  'text' : string,
  'author' : string,
  'isVisible' : boolean,
}
export type Timestamp = bigint;
export interface TrainingModule {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'videoStorageId' : [] | [string],
  'createdAt' : Timestamp,
  'description' : string,
  'textContent' : string,
}
export interface UpdateProjectRequest {
  'completedDate' : [] | [Timestamp],
  'status' : [] | [ClientProjectStatus],
  'projectDescription' : [] | [string],
  'projectTitle' : [] | [string],
  'expectedEndDate' : [] | [Timestamp],
}
export type UserRole = { 'Customer' : null } |
  { 'Staff' : null } |
  { 'PlatformOwner' : null } |
  { 'Affiliate' : null } |
  { 'Admin' : null };
export interface VersionInfo {
  'systemVersion' : string,
  'buildVersion' : bigint,
  'lastDeployedAt' : bigint,
  'environment' : string,
}
export interface _SERVICE {
  '_internalCreateLeadFromContact' : ActorMethod<
    [string, string, string, [] | [string], bigint],
    undefined
  >,
  'adminAddDeliverable' : ActorMethod<
    [string, Deliverable],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminAddFinanceEntry' : ActorMethod<
    [EntryType, bigint, string, string],
    undefined
  >,
  'adminAddGalleryImage' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminAddGalleryVideo' : ActorMethod<
    [GalleryVideoInput],
    { 'ok' : GalleryVideo } |
      { 'err' : string }
  >,
  'adminAddNextStep' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminAddOrder' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      string,
      [] | [Principal],
      [] | [Principal],
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminAddPayout' : ActorMethod<
    [PayoutRecord],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminAddSystemApp' : ActorMethod<
    [string, string, string],
    { 'ok' : SystemApp } |
      { 'err' : string }
  >,
  'adminAddUpdate' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminAdjustCommission' : ActorMethod<
    [string, number, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminApproveAffiliate' : ActorMethod<
    [Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminApprovePaymentOrder' : ActorMethod<
    [bigint, boolean, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminBlockKey' : ActorMethod<[string, string], undefined>,
  'adminCreateLiveSession' : ActorMethod<
    [string, string, bigint, string],
    undefined
  >,
  'adminCreateProject' : ActorMethod<
    [CreateProjectRequest],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminCreateTrainingModule' : ActorMethod<
    [string, string, [] | [string], string, bigint],
    undefined
  >,
  'adminDeleteFinanceEntry' : ActorMethod<[bigint], undefined>,
  'adminDeleteGalleryImage' : ActorMethod<[bigint], undefined>,
  'adminDeleteGalleryVideo' : ActorMethod<[bigint], undefined>,
  'adminDeleteLiveSession' : ActorMethod<[bigint], undefined>,
  'adminDeleteSystemApp' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminDeleteTrainingModule' : ActorMethod<[bigint], undefined>,
  'adminDisableAffiliate' : ActorMethod<
    [Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminEditGalleryVideo' : ActorMethod<
    [bigint, GalleryVideoInput],
    { 'ok' : GalleryVideo } |
      { 'err' : string }
  >,
  'adminEditSystemApp' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminGetAffiliateStats' : ActorMethod<[string], AffiliateStats>,
  'adminGetAffiliates' : ActorMethod<[], Array<AffiliateProfile>>,
  'adminGetAllContactPlatforms' : ActorMethod<[], Array<ContactPlatform>>,
  'adminGetAllLegalContent' : ActorMethod<[], Array<LegalContent>>,
  'adminGetAllProjects' : ActorMethod<
    [],
    { 'ok' : Array<ClientProject> } |
      { 'err' : string }
  >,
  'adminGetAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'adminGetBlockedKeys' : ActorMethod<[], Array<BlockEntry>>,
  'adminGetBrandTagline' : ActorMethod<[], string>,
  'adminGetCompetenceCards' : ActorMethod<[], Array<CompetenceCard>>,
  'adminGetCompetenceSectionVisible' : ActorMethod<[], boolean>,
  'adminGetContactLinks' : ActorMethod<[], ContactLinks>,
  'adminGetContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'adminGetCryptoPaymentConfig' : ActorMethod<
    [],
    { 'ok' : CryptoPaymentConfig } |
      { 'err' : string }
  >,
  'adminGetDeploymentLog' : ActorMethod<[], Array<DeploymentEntry>>,
  'adminGetFinanceEntries' : ActorMethod<[], Array<FinanceEntry>>,
  'adminGetFinanceSummary' : ActorMethod<[], FinanceSummary>,
  'adminGetGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'adminGetGalleryVideos' : ActorMethod<[], Array<GalleryVideo>>,
  'adminGetHeroImageIds' : ActorMethod<[], HeroImageIds>,
  'adminGetLead' : ActorMethod<[string], [] | [Lead]>,
  'adminGetLeadStats' : ActorMethod<[], LeadStats>,
  'adminGetLeads' : ActorMethod<[LeadFilter], Array<Lead>>,
  'adminGetOrder' : ActorMethod<[string], [] | [Order]>,
  'adminGetOrders' : ActorMethod<[SalesFilter], Array<Order>>,
  'adminGetPaymentConfig' : ActorMethod<[], PaymentConfig>,
  'adminGetPayoutHistory' : ActorMethod<[string], Array<PayoutRecord>>,
  'adminGetPricingData' : ActorMethod<[], PricingData>,
  'adminGetProjectById' : ActorMethod<
    [string],
    { 'ok' : ClientProject } |
      { 'err' : string }
  >,
  'adminGetSalesStats' : ActorMethod<[], SalesStats>,
  'adminGetSecurityPolicy' : ActorMethod<[], SecurityPolicy>,
  'adminGetSystemsApps' : ActorMethod<[], Array<SystemApp>>,
  'adminGetTrainingModules' : ActorMethod<[], Array<TrainingModule>>,
  'adminListAuditLogs' : ActorMethod<[[] | [bigint]], Array<AuditLog>>,
  'adminListBuyerLeads' : ActorMethod<
    [[] | [BuyerLeadStatus], [] | [FormSource]],
    Array<BuyerLead>
  >,
  'adminListPaymentOrders' : ActorMethod<[], Array<PaymentOrder>>,
  'adminRegisterAffiliate' : ActorMethod<
    [Principal, string, string, string],
    undefined
  >,
  'adminRejectAffiliate' : ActorMethod<
    [Principal, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminReorderPlatform' : ActorMethod<
    [string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetAbout' : ActorMethod<[AboutSection], undefined>,
  'adminSetBrandTagline' : ActorMethod<[string], undefined>,
  'adminSetBundles' : ActorMethod<
    [Array<Bundle>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetCommission' : ActorMethod<
    [CommissionSettings],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetCompetenceCards' : ActorMethod<[Array<CompetenceCard>], undefined>,
  'adminSetCompetencePricing' : ActorMethod<
    [Array<CompetencePricing>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetCompetenceSectionVisible' : ActorMethod<[boolean], undefined>,
  'adminSetConsultancyServices' : ActorMethod<
    [Array<ConsultancyService>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetContactDetails' : ActorMethod<
    [ContactDetails],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetContactLinks' : ActorMethod<[ContactLinks], undefined>,
  'adminSetContactPlatforms' : ActorMethod<
    [Array<ContactPlatform>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetCryptoPaymentConfig' : ActorMethod<
    [CryptoPaymentConfig],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetGiveaways' : ActorMethod<
    [Array<GiveawayItem>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetHelpBlocks' : ActorMethod<[Array<HelpBlock>], undefined>,
  'adminSetHeroImageIds' : ActorMethod<[HeroImageIds], undefined>,
  'adminSetHeroSlides' : ActorMethod<[Array<HeroSlide>], undefined>,
  'adminSetLandingPageOffers' : ActorMethod<
    [Array<LandingPageOffer>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetLegalContent' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSetPaymentConfig' : ActorMethod<
    [PaymentConfig],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetSecurityPolicy' : ActorMethod<
    [SecurityPolicy],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetSignatureEdge' : ActorMethod<[SignatureEdge], undefined>,
  'adminSetTestimonials' : ActorMethod<[Array<Testimonial>], undefined>,
  'adminSetWebhookSecretHash' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminToggleGalleryVideoFeatured' : ActorMethod<
    [bigint],
    { 'ok' : GalleryVideo } |
      { 'err' : string }
  >,
  'adminToggleGalleryVideoVisibility' : ActorMethod<
    [bigint],
    { 'ok' : GalleryVideo } |
      { 'err' : string }
  >,
  'adminTogglePlatformVisibility' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'adminTogglePricingItemVisibility' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'adminToggleSystemApp' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'adminUnblockKey' : ActorMethod<[string], undefined>,
  'adminUpdateBuyerLeadStatus' : ActorMethod<
    [bigint, BuyerLeadStatus, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminUpdateLead' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      LeadSource,
      LeadStatus,
      string,
      [] | [Principal],
      [] | [string],
      bigint,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminUpdateLiveSession' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'adminUpdateNextStep' : ActorMethod<
    [string, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      OrderStatus,
      string,
      [] | [Principal],
      [] | [Principal],
      bigint,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminUpdatePayoutRecord' : ActorMethod<
    [string, PayoutStatus, [] | [Principal], string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminUpdateProject' : ActorMethod<
    [string, UpdateProjectRequest],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateSystemConfig' : ActorMethod<
    [SystemConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateTrainingModule' : ActorMethod<
    [bigint, string, string, [] | [string], string, bigint],
    undefined
  >,
  'affiliateGetInviteLink' : ActorMethod<[], string>,
  'affiliateGetPayoutHistory' : ActorMethod<[], Array<PayoutRecord>>,
  'affiliateGetProfile' : ActorMethod<[], AffiliateProfile>,
  'affiliateGetStats' : ActorMethod<[], AffiliateStats>,
  'affiliateRequestPayout' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'assignUserRole' : ActorMethod<
    [Principal, UserRole, string, Array<Permission>],
    RoleResult
  >,
  'claimOwnership' : ActorMethod<[string], RoleResult>,
  'clientGetMyProject' : ActorMethod<
    [],
    { 'ok' : ClientProject } |
      { 'err' : string }
  >,
  'confirmOwnership' : ActorMethod<
    [],
    { 'role' : [] | [UserRole], 'isOwnerOrAdmin' : boolean }
  >,
  'createPaymentOrder' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      { 'localBank' : null } |
        { 'paystack' : null } |
        { 'flutterwave' : null },
    ],
    { 'ok' : PaymentOrder } |
      { 'err' : string }
  >,
  'flutterwaveWebhook' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAbout' : ActorMethod<[], AboutSection>,
  'getActivityLog' : ActorMethod<[bigint], Array<ActivityLog>>,
  'getBrandTagline' : ActorMethod<[], string>,
  'getCompetenceCards' : ActorMethod<[], Array<CompetenceCard>>,
  'getCompetenceCardsVisible' : ActorMethod<[], Array<CompetenceCard>>,
  'getCompetenceSectionVisible' : ActorMethod<[], boolean>,
  'getContactDetails' : ActorMethod<[], ContactDetails>,
  'getContactLinks' : ActorMethod<[], ContactLinks>,
  'getContactPlatforms' : ActorMethod<[], Array<ContactPlatform>>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getGalleryVideos' : ActorMethod<[], Array<GalleryVideo>>,
  'getHelpBlocks' : ActorMethod<[], Array<HelpBlock>>,
  'getHeroImageIds' : ActorMethod<[], HeroImageIds>,
  'getHeroSlides' : ActorMethod<[], Array<HeroSlide>>,
  'getLegalContent' : ActorMethod<[string], [] | [LegalContent]>,
  'getLiveSessions' : ActorMethod<[], Array<LiveSession>>,
  'getMyRole' : ActorMethod<[], [] | [UserRole]>,
  'getOwnerDebugInfo' : ActorMethod<
    [],
    {
      'ownerEmail' : string,
      'callerRole' : string,
      'callerIsOwner' : boolean,
      'callerEmail' : [] | [string],
    }
  >,
  'getPaymentConfig' : ActorMethod<[], PaymentConfigPublic>,
  'getPricingData' : ActorMethod<[], PricingData>,
  'getPublicCryptoPaymentInfo' : ActorMethod<[], [] | [CryptoPaymentPublic]>,
  'getSignatureEdge' : ActorMethod<[], SignatureEdge>,
  'getSystemConfig' : ActorMethod<[], SystemConfig>,
  'getSystemsApps' : ActorMethod<[], Array<SystemApp>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTrainingModules' : ActorMethod<[], Array<TrainingModule>>,
  'getUserRole' : ActorMethod<[Principal], [] | [UserRole]>,
  'getVersionInfo' : ActorMethod<[], VersionInfo>,
  'getVisibleTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'listUsersByRole' : ActorMethod<[UserRole], Array<StaffUser>>,
  'paystackWebhook' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'revokeUserRole' : ActorMethod<[Principal], RoleResult>,
  'submitBuyerLead' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      FormSource,
      string,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitContactMessage' : ActorMethod<[string, string, string], SubmitResult>,
  'trackReferralClick' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];